// Code generated by MockGen. DO NOT EDIT.
// Source: services/barang_service.go

// Package mock_services is a generated GoMock package.
package mock_services

import (
	context "context"
	reflect "reflect"
	models "warehouse/models"

	gomock "github.com/golang/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockBarangRepo is a mock of BarangRepo interface.
type MockBarangRepo struct {
	ctrl     *gomock.Controller
	recorder *MockBarangRepoMockRecorder
}

// MockBarangRepoMockRecorder is the mock recorder for MockBarangRepo.
type MockBarangRepoMockRecorder struct {
	mock *MockBarangRepo
}

// NewMockBarangRepo creates a new mock instance.
func NewMockBarangRepo(ctrl *gomock.Controller) *MockBarangRepo {
	mock := &MockBarangRepo{ctrl: ctrl}
	mock.recorder = &MockBarangRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBarangRepo) EXPECT() *MockBarangRepoMockRecorder {
	return m.recorder
}

// CreateBarang mocks base method.
func (m *MockBarangRepo) CreateBarang(tx *gorm.DB, data models.MasterBarang) (*models.MasterBarang, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBarang", tx, data)
	ret0, _ := ret[0].(*models.MasterBarang)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBarang indicates an expected call of CreateBarang.
func (mr *MockBarangRepoMockRecorder) CreateBarang(tx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBarang", reflect.TypeOf((*MockBarangRepo)(nil).CreateBarang), tx, data)
}

// DeleteBarang mocks base method.
func (m *MockBarangRepo) DeleteBarang(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBarang", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBarang indicates an expected call of DeleteBarang.
func (mr *MockBarangRepoMockRecorder) DeleteBarang(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBarang", reflect.TypeOf((*MockBarangRepo)(nil).DeleteBarang), ctx, id)
}

// GetAllBarang mocks base method.
func (m *MockBarangRepo) GetAllBarang(ctx context.Context, search string, offset, limit int) ([]models.MasterBarang, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllBarang", ctx, search, offset, limit)
	ret0, _ := ret[0].([]models.MasterBarang)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAllBarang indicates an expected call of GetAllBarang.
func (mr *MockBarangRepoMockRecorder) GetAllBarang(ctx, search, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllBarang", reflect.TypeOf((*MockBarangRepo)(nil).GetAllBarang), ctx, search, offset, limit)
}

// GetAllBarangWithStok mocks base method.
func (m *MockBarangRepo) GetAllBarangWithStok(ctx context.Context, offset, limit int) ([]models.MasterBarangWithStok, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllBarangWithStok", ctx, offset, limit)
	ret0, _ := ret[0].([]models.MasterBarangWithStok)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAllBarangWithStok indicates an expected call of GetAllBarangWithStok.
func (mr *MockBarangRepoMockRecorder) GetAllBarangWithStok(ctx, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllBarangWithStok", reflect.TypeOf((*MockBarangRepo)(nil).GetAllBarangWithStok), ctx, offset, limit)
}

// GetBarang mocks base method.
func (m *MockBarangRepo) GetBarang(tx *gorm.DB, id int) (*models.MasterBarang, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBarang", tx, id)
	ret0, _ := ret[0].(*models.MasterBarang)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBarang indicates an expected call of GetBarang.
func (mr *MockBarangRepoMockRecorder) GetBarang(tx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBarang", reflect.TypeOf((*MockBarangRepo)(nil).GetBarang), tx, id)
}

// UpdateBarang mocks base method.
func (m *MockBarangRepo) UpdateBarang(tx *gorm.DB, data models.MasterBarang) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBarang", tx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBarang indicates an expected call of UpdateBarang.
func (mr *MockBarangRepoMockRecorder) UpdateBarang(tx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBarang", reflect.TypeOf((*MockBarangRepo)(nil).UpdateBarang), tx, data)
}
