// Code generated by MockGen. DO NOT EDIT.
// Source: services/pembelian_service.go

// Package mock_services is a generated GoMock package.
package mock_services

import (
	context "context"
	reflect "reflect"
	models "warehouse/models"

	gomock "github.com/golang/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockPembelianRepo is a mock of PembelianRepo interface.
type MockPembelianRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPembelianRepoMockRecorder
}

// MockPembelianRepoMockRecorder is the mock recorder for MockPembelianRepo.
type MockPembelianRepoMockRecorder struct {
	mock *MockPembelianRepo
}

// NewMockPembelianRepo creates a new mock instance.
func NewMockPembelianRepo(ctrl *gomock.Controller) *MockPembelianRepo {
	mock := &MockPembelianRepo{ctrl: ctrl}
	mock.recorder = &MockPembelianRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPembelianRepo) EXPECT() *MockPembelianRepoMockRecorder {
	return m.recorder
}

// CreateBeliDetail mocks base method.
func (m *MockPembelianRepo) CreateBeliDetail(tx *gorm.DB, data models.BeliDetail) (*models.BeliDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBeliDetail", tx, data)
	ret0, _ := ret[0].(*models.BeliDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBeliDetail indicates an expected call of CreateBeliDetail.
func (mr *MockPembelianRepoMockRecorder) CreateBeliDetail(tx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBeliDetail", reflect.TypeOf((*MockPembelianRepo)(nil).CreateBeliDetail), tx, data)
}

// CreateBeliHeader mocks base method.
func (m *MockPembelianRepo) CreateBeliHeader(tx *gorm.DB, data models.BeliHeader) (*models.BeliHeader, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBeliHeader", tx, data)
	ret0, _ := ret[0].(*models.BeliHeader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBeliHeader indicates an expected call of CreateBeliHeader.
func (mr *MockPembelianRepoMockRecorder) CreateBeliHeader(tx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBeliHeader", reflect.TypeOf((*MockPembelianRepo)(nil).CreateBeliHeader), tx, data)
}

// GetAllPembelian mocks base method.
func (m *MockPembelianRepo) GetAllPembelian(ctx context.Context, offset, limit int) ([]models.BeliHeader, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllPembelian", ctx, offset, limit)
	ret0, _ := ret[0].([]models.BeliHeader)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAllPembelian indicates an expected call of GetAllPembelian.
func (mr *MockPembelianRepoMockRecorder) GetAllPembelian(ctx, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPembelian", reflect.TypeOf((*MockPembelianRepo)(nil).GetAllPembelian), ctx, offset, limit)
}

// GetPembelian mocks base method.
func (m *MockPembelianRepo) GetPembelian(ctx context.Context, beliID int) (*models.Pembelian, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPembelian", ctx, beliID)
	ret0, _ := ret[0].(*models.Pembelian)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPembelian indicates an expected call of GetPembelian.
func (mr *MockPembelianRepoMockRecorder) GetPembelian(ctx, beliID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPembelian", reflect.TypeOf((*MockPembelianRepo)(nil).GetPembelian), ctx, beliID)
}

// UpdateBeliDetail mocks base method.
func (m *MockPembelianRepo) UpdateBeliDetail(tx *gorm.DB, data models.BeliDetail) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBeliDetail", tx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBeliDetail indicates an expected call of UpdateBeliDetail.
func (mr *MockPembelianRepoMockRecorder) UpdateBeliDetail(tx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBeliDetail", reflect.TypeOf((*MockPembelianRepo)(nil).UpdateBeliDetail), tx, data)
}

// UpdateBeliHeader mocks base method.
func (m *MockPembelianRepo) UpdateBeliHeader(tx *gorm.DB, data models.BeliHeader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBeliHeader", tx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBeliHeader indicates an expected call of UpdateBeliHeader.
func (mr *MockPembelianRepoMockRecorder) UpdateBeliHeader(tx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBeliHeader", reflect.TypeOf((*MockPembelianRepo)(nil).UpdateBeliHeader), tx, data)
}
