// Code generated by MockGen. DO NOT EDIT.
// Source: services/penjualan_service.go

// Package mock_services is a generated GoMock package.
package mock_services

import (
	context "context"
	reflect "reflect"
	models "warehouse/models"

	gomock "github.com/golang/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockPenjualanRepo is a mock of PenjualanRepo interface.
type MockPenjualanRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPenjualanRepoMockRecorder
}

// MockPenjualanRepoMockRecorder is the mock recorder for MockPenjualanRepo.
type MockPenjualanRepoMockRecorder struct {
	mock *MockPenjualanRepo
}

// NewMockPenjualanRepo creates a new mock instance.
func NewMockPenjualanRepo(ctrl *gomock.Controller) *MockPenjualanRepo {
	mock := &MockPenjualanRepo{ctrl: ctrl}
	mock.recorder = &MockPenjualanRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPenjualanRepo) EXPECT() *MockPenjualanRepoMockRecorder {
	return m.recorder
}

// CreateJualDetail mocks base method.
func (m *MockPenjualanRepo) CreateJualDetail(tx *gorm.DB, data models.JualDetail) (*models.JualDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateJualDetail", tx, data)
	ret0, _ := ret[0].(*models.JualDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateJualDetail indicates an expected call of CreateJualDetail.
func (mr *MockPenjualanRepoMockRecorder) CreateJualDetail(tx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateJualDetail", reflect.TypeOf((*MockPenjualanRepo)(nil).CreateJualDetail), tx, data)
}

// CreateJualHeader mocks base method.
func (m *MockPenjualanRepo) CreateJualHeader(tx *gorm.DB, data models.JualHeader) (*models.JualHeader, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateJualHeader", tx, data)
	ret0, _ := ret[0].(*models.JualHeader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateJualHeader indicates an expected call of CreateJualHeader.
func (mr *MockPenjualanRepoMockRecorder) CreateJualHeader(tx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateJualHeader", reflect.TypeOf((*MockPenjualanRepo)(nil).CreateJualHeader), tx, data)
}

// GetAllPenjualan mocks base method.
func (m *MockPenjualanRepo) GetAllPenjualan(ctx context.Context, offset, limit int) ([]models.JualHeader, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllPenjualan", ctx, offset, limit)
	ret0, _ := ret[0].([]models.JualHeader)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAllPenjualan indicates an expected call of GetAllPenjualan.
func (mr *MockPenjualanRepoMockRecorder) GetAllPenjualan(ctx, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPenjualan", reflect.TypeOf((*MockPenjualanRepo)(nil).GetAllPenjualan), ctx, offset, limit)
}

// GetPenjualan mocks base method.
func (m *MockPenjualanRepo) GetPenjualan(ctx context.Context, jualID int) (*models.Penjualan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPenjualan", ctx, jualID)
	ret0, _ := ret[0].(*models.Penjualan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPenjualan indicates an expected call of GetPenjualan.
func (mr *MockPenjualanRepoMockRecorder) GetPenjualan(ctx, jualID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPenjualan", reflect.TypeOf((*MockPenjualanRepo)(nil).GetPenjualan), ctx, jualID)
}

// UpdateJualDetail mocks base method.
func (m *MockPenjualanRepo) UpdateJualDetail(tx *gorm.DB, data models.JualDetail) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateJualDetail", tx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateJualDetail indicates an expected call of UpdateJualDetail.
func (mr *MockPenjualanRepoMockRecorder) UpdateJualDetail(tx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateJualDetail", reflect.TypeOf((*MockPenjualanRepo)(nil).UpdateJualDetail), tx, data)
}

// UpdateJualHeader mocks base method.
func (m *MockPenjualanRepo) UpdateJualHeader(tx *gorm.DB, data models.JualHeader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateJualHeader", tx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateJualHeader indicates an expected call of UpdateJualHeader.
func (mr *MockPenjualanRepoMockRecorder) UpdateJualHeader(tx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateJualHeader", reflect.TypeOf((*MockPenjualanRepo)(nil).UpdateJualHeader), tx, data)
}
