// Code generated by MockGen. DO NOT EDIT.
// Source: services/stok_service.go

// Package mock_services is a generated GoMock package.
package mock_services

import (
	context "context"
	reflect "reflect"
	models "warehouse/models"

	gomock "github.com/golang/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockStokRepo is a mock of StokRepo interface.
type MockStokRepo struct {
	ctrl     *gomock.Controller
	recorder *MockStokRepoMockRecorder
}

// MockStokRepoMockRecorder is the mock recorder for MockStokRepo.
type MockStokRepoMockRecorder struct {
	mock *MockStokRepo
}

// NewMockStokRepo creates a new mock instance.
func NewMockStokRepo(ctrl *gomock.Controller) *MockStokRepo {
	mock := &MockStokRepo{ctrl: ctrl}
	mock.recorder = &MockStokRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStokRepo) EXPECT() *MockStokRepoMockRecorder {
	return m.recorder
}

// CreateHistoryStok mocks base method.
func (m *MockStokRepo) CreateHistoryStok(tx *gorm.DB, data models.HistoryStok) (*models.HistoryStok, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateHistoryStok", tx, data)
	ret0, _ := ret[0].(*models.HistoryStok)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateHistoryStok indicates an expected call of CreateHistoryStok.
func (mr *MockStokRepoMockRecorder) CreateHistoryStok(tx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateHistoryStok", reflect.TypeOf((*MockStokRepo)(nil).CreateHistoryStok), tx, data)
}

// CreateStok mocks base method.
func (m *MockStokRepo) CreateStok(tx *gorm.DB, data models.Mstok) (*models.Mstok, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStok", tx, data)
	ret0, _ := ret[0].(*models.Mstok)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStok indicates an expected call of CreateStok.
func (mr *MockStokRepoMockRecorder) CreateStok(tx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStok", reflect.TypeOf((*MockStokRepo)(nil).CreateStok), tx, data)
}

// DeleteStok mocks base method.
func (m *MockStokRepo) DeleteStok(tx *gorm.DB, barangID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStok", tx, barangID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteStok indicates an expected call of DeleteStok.
func (mr *MockStokRepoMockRecorder) DeleteStok(tx, barangID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStok", reflect.TypeOf((*MockStokRepo)(nil).DeleteStok), tx, barangID)
}

// GetAllStok mocks base method.
func (m *MockStokRepo) GetAllStok(ctx context.Context, offset, limit int) ([]models.Mstok, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllStok", ctx, offset, limit)
	ret0, _ := ret[0].([]models.Mstok)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAllStok indicates an expected call of GetAllStok.
func (mr *MockStokRepoMockRecorder) GetAllStok(ctx, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllStok", reflect.TypeOf((*MockStokRepo)(nil).GetAllStok), ctx, offset, limit)
}

// GetHistoryStok mocks base method.
func (m *MockStokRepo) GetHistoryStok(ctx context.Context, offset, limit int) ([]models.HistoryStok, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistoryStok", ctx, offset, limit)
	ret0, _ := ret[0].([]models.HistoryStok)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetHistoryStok indicates an expected call of GetHistoryStok.
func (mr *MockStokRepoMockRecorder) GetHistoryStok(ctx, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistoryStok", reflect.TypeOf((*MockStokRepo)(nil).GetHistoryStok), ctx, offset, limit)
}

// GetHistoryStokByBarangID mocks base method.
func (m *MockStokRepo) GetHistoryStokByBarangID(ctx context.Context, barangID int) ([]models.HistoryStok, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistoryStokByBarangID", ctx, barangID)
	ret0, _ := ret[0].([]models.HistoryStok)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHistoryStokByBarangID indicates an expected call of GetHistoryStokByBarangID.
func (mr *MockStokRepoMockRecorder) GetHistoryStokByBarangID(ctx, barangID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistoryStokByBarangID", reflect.TypeOf((*MockStokRepo)(nil).GetHistoryStokByBarangID), ctx, barangID)
}

// GetStokByBarangID mocks base method.
func (m *MockStokRepo) GetStokByBarangID(tx *gorm.DB, barangID int) (*models.Mstok, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStokByBarangID", tx, barangID)
	ret0, _ := ret[0].(*models.Mstok)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStokByBarangID indicates an expected call of GetStokByBarangID.
func (mr *MockStokRepoMockRecorder) GetStokByBarangID(tx, barangID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStokByBarangID", reflect.TypeOf((*MockStokRepo)(nil).GetStokByBarangID), tx, barangID)
}

// LockStok mocks base method.
func (m *MockStokRepo) LockStok(tx *gorm.DB, barangID int) (*models.Mstok, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockStok", tx, barangID)
	ret0, _ := ret[0].(*models.Mstok)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LockStok indicates an expected call of LockStok.
func (mr *MockStokRepoMockRecorder) LockStok(tx, barangID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockStok", reflect.TypeOf((*MockStokRepo)(nil).LockStok), tx, barangID)
}

// UpdateStok mocks base method.
func (m *MockStokRepo) UpdateStok(tx *gorm.DB, barangID, stok int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStok", tx, barangID, stok)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStok indicates an expected call of UpdateStok.
func (mr *MockStokRepoMockRecorder) UpdateStok(tx, barangID, stok interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStok", reflect.TypeOf((*MockStokRepo)(nil).UpdateStok), tx, barangID, stok)
}
